%YAML:1.0

device_param: 1 # 0: cpu; 1: gpu

shift_map: 1 # 0: disable will also disable decoder_freeze; 1: enable; Whether the map shift with input pose
decoder_freeze_frame_num: 100 # -1: disable

online: 1 # 0: offline; 1: online(ros)

# online params
depth_type: 0 # 0: lidar; 1: depth img
depth_topic: "/cloud_registered_body"
pose_msg_type: 0 # 0: nav_msgs/Odometry 1: geometry_msgs/PoseStamped; 2: geometry_msgs/TransformStamped
pose_topic: "/Odometry"
frame_rate: 10

# From sensor to body(pose_topic)
T_B_S: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [ 1, 0, 0, 0.04165,
           0, 1, 0, 0.02326,
           0, 0, 1, -0.0284]
inv_extrinsic: 0

min_range: 0.3
ds_pt_num: 10000 # downsampled point number
max_pt_num: 1000000

x_max: 10
x_min: -10
y_max: 10
y_min: -10
z_max: 5
z_min: -3

leaf_sizes: 0.1
layer_num: 3

batch_pt_num: 2048
batch_type: 2 # 0: random; 1: slice; 2: even random

iter_step: 10
feat_dim: 4
hidden_dim: 32
multifeat_type: 0 # 0:concat; 1:sum
lr: 2e-3

sample_std: 0.1 # smaller thiner and less smoother surface, equal to max vox size might be a good choice
surface_sample_num: 3
free_sample_num: 3
strat_near_ratio: 0.2
strat_far_ratio: 0.8
use_outrange: 1
out_sample_num: 3
hist_pt: 1
zero_init: 1
outlier_remove: 1
outlier_dist: 0.05

supervise_mode: 1 # 0:tsdf; 1:bce_sdf
bce_sigma: 0.5 # higher be more robust to outliers
eikonal: 0 # disable if no need for continuous sdf, and lower lr
eikonal_weight: 0.1
positional_encoding: 0
dist_type: 0 # 0:SRD(Signed Ray Distance); 1:nearest point

# visualization
large_scene: 0 # 0: disable(prepare 40G memory for kitti 00); 1: enable, enable to aovid crashing cause by out of memorty (both cpu and gpu)
save_normal: 0 # 0: disable to save storage
eval_mode: 1 # -1: diable meshing; 0: meshing input voxel; 1: meshing local map (enable for sdf map)
vis_frame_step: 10
vis_batch_pt_num: 1e6 # lower it if OOM(Out of Memory) or any unkown error
vis_resolution: 0.1
export_resolution: 0.02
downsample_mesh_size: 0 # 0: disable; enable to compace faces but might lead to loss of accuracy and segment fault(OOM)
skip_unconf: 1
slice_height: -0.5 # relative to the pose's height